### ISSUE TITLE
global: fix build failure

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/pytest-invenio#42]
Same as:
* [pytest-invenio #42](https://github.com/inveniosoftware/pytest-invenio/issues/42)
* [invenio-oauth2server #196](https://github.com/inveniosoftware/invenio-oauth2server/issues/196)

https://travis-ci.org/inveniosoftware/pytest-invenio/jobs/656682655
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 185, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 648, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 820, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 772, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/opt/python/2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 290, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pytest_flask/plugin.py", line 12, in <module>
    from werkzeug import cached_property
ImportError: cannot import name cached_property
The command "./run-tests.sh" exited with 1.
```

Fix also deprecation warning in Travis config:
https://travis-ci.org/inveniosoftware/pytest-invenio/jobs/656682655/config

**Comment by kprzerwa** [comment]
so far, fixed werkzeug problems until 
https://github.com/kprzerwa/pytest-invenio/tree/update-deps
